---
- name: Update package lists
  apt:
    update_cache: true

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Install default packages
  apt:
    name:
      - apt-transport-https
      - zip
      - git
      - curl
      - vim
      - tree

- name: Set hostname
  hostname:
    name: "{{ hostname }}"
